name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore 
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --configuration release --output aspnet-webapp -p:PublishSingleFile=true --self-contained false
    - name: Upload Aritfact
      uses: actions/upload-artifact@v2        
      with:
        name: webapp
        path: aspnet-webapp
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hellowebf1'
        publish-profile: ${{ secrets.WEBAPP_PUBLISH_PROFILE }}
        package: './aspnet-webapp'
        
